### ISSUE TITLE
天选时刻无法加载

### ISSUE THREAD

**Issue by Chikaze** [SeaLoong/BLRHH#98]
天选时刻模块无法正常加载,仅显示框架,无内容.

**Comment by HYY-zh** [comment]
天选是特意屏蔽的

**Comment by EuropeanWithSSR** [comment]
点击“天选时刻”后console的信息：
`VM4876 chunk-common.c8e581eb.js:5 Uncaught (in promise) DOMException: Blocked a frame with origin "https://live.bilibili.com" from accessing a cross-origin frame.
    at r (https://s1.hdslb.com/bfs/static/blive/live-lottery/static/js/chunk-common.c8e581eb.js:5:10174)
    at https://s1.hdslb.com/bfs/static/blive/live-lottery/static/js/chunk-common.c8e581eb.js:5:15356
    at u (https://s1.hdslb.com/bfs/static/blive/live-lottery/static/js/chunk-vendors.4a627918.js:29:28692)
    at Generator._invoke (https://s1.hdslb.com/bfs/static/blive/live-lottery/static/js/chunk-vendors.4a627918.js:29:30014)
    at Generator.forEach.e.<computed> [as next] (https://s1.hdslb.com/bfs/static/blive/live-lottery/static/js/chunk-vendors.4a627918.js:29:29115)
    at o (https://s1.hdslb.com/bfs/static/blive/live-lottery/static/js/chunk-vendors.4a627918.js:12:39871)
    at s (https://s1.hdslb.com/bfs/static/blive/live-lottery/static/js/chunk-vendors.4a627918.js:12:40066)
    at https://s1.hdslb.com/bfs/static/blive/live-lottery/static/js/chunk-vendors.4a627918.js:12:40125
    at new Promise (<anonymous>)
    at new t (https://s1.hdslb.com/bfs/static/blive/live-lottery/static/js/chunk-vendors.4a627918.js:17:18233)`
